[project]
name = "qt-video-player"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cython>=3.0.12",
    "opencv-python>=4.11.0.86",
    "pyqt6>=6.8.1",
    "setuptools>=75.8.1",
]
